In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("icc.csv")

In [3]:
df

,player,dismissal,runs,balls,minutes,4s,6s,strike_rate,team,opponent,innings,match_id
0,Rohit Sharma,b Madushanka,4,2,2,1,0,200.00,India,Sri Lanka,1,0
1,Shubman Gill,c Mendis b Madushanka,92,92,136,11,2,100.00,India,Sri Lanka,1,0
2,Virat Kohli,c Nissanka b Madushanka,88,94,139,11,0,93.61,India,Sri Lanka,1,0
3,Shreyas Iyer,c Theekshana b Madushanka,82,56,84,3,6,146.42,India,Sri Lanka,1,0
4,KL Rahul,c Hemantha b Chameera,21,19,34,2,0,110.52,India,Sri Lanka,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
870,Iftikhar Ahmed,c Malan b Ali,3,5,8,0,0,60.00,Pakistan,England,2,47
871,Shadab Khan,b Rashid,4,7,4,1,0,57.14,Pakistan,England,2,47
872,Shaheen Shah Afridi,lbw b Atkinson,25,23,23,3,1,108.69,Pakistan,England,2,47
873,Mohammad Wasim,not out,16,14,33,2,1,114.28,Pakistan,England,2,47
874,Haris Rauf,c Stokes b Woakes,35,23,27,3,3,152.17,Pakistan,England,2,47

In [6]:
for i in df:
    if i

KeyError: 'Rohit Sharma'